### PR TITLE
Swift 5, Xcode 10, fix warnings

### PR DESCRIPTION
**Pull request by krezzoid**
Swift 5, Xcode 10, fix warnings
bump up version

### CODE REVIEW

**Comment by readefries** [comment]
Can you rebase? I updated the travis configuration, and I couldn't push to your fork.

**Comment by readefries** [comment]
Sorry, I accidentally added Xcode 10.1 instead of Xcode 10.2 :( 
Can you rebase again?

**Comment by krezzoid** [comment]
@readefries done, now everything should be ok :)

**Comment by readefries** [comment]
I cherry-picked your changes, and commited them to master.
Version 3.0.3 is released which contains these.

**Pull request closed without merging**
